-- ─────────────────────────────────────────────────────────────────────────────
-- LGS Growth Dashboard — Supabase schema v1
-- Paste this whole file into Supabase Dashboard → SQL Editor → Run.
-- Safe to re-run (everything uses IF NOT EXISTS / ON CONFLICT DO NOTHING).
-- ─────────────────────────────────────────────────────────────────────────────

create extension if not exists "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. page_view_events — top of funnel, browser pixel fires this on every page
--    Stores fingerprint + fbclid + UTMs so anonymous sessions can later be
--    anchored to a known contact once they opt in.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.page_view_events (
  id              bigint generated by default as identity primary key,
  event_id        text unique not null,
  event_name      text not null default 'PageView',
  event_time      timestamptz not null default now(),
  page_url        text,
  referrer        text,
  -- Identity signals
  fingerprint     text,                   -- ThumbmarkJS visitor ID (when wired)
  fbclid          text,
  fbp             text,
  fbc             text,
  -- UTMs
  utm_source      text,
  utm_medium      text,
  utm_campaign    text,
  utm_content     text,                   -- ad name
  utm_term        text,                   -- adset name
  -- Network
  client_ip       inet,
  user_agent      text,
  -- Linkage
  contact_id      bigint,                 -- set later when opt-in fires; FK below
  created_at      timestamptz not null default now()
);

create index if not exists idx_pve_event_time   on public.page_view_events (event_time desc);
create index if not exists idx_pve_fingerprint  on public.page_view_events (fingerprint);
create index if not exists idx_pve_fbclid       on public.page_view_events (fbclid);
create index if not exists idx_pve_utm_campaign on public.page_view_events (utm_campaign);
create index if not exists idx_pve_utm_content  on public.page_view_events (utm_content);
create index if not exists idx_pve_contact_id   on public.page_view_events (contact_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. ghl_contacts — anchors fingerprint/fbclid to a real person on form submit
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.ghl_contacts (
  id                   bigint generated by default as identity primary key,
  ghl_contact_id       text unique not null,
  -- PII
  email                text,
  first_name           text,
  last_name            text,
  phone                text,
  -- Attribution (denormalized for cheap reads)
  utm_source           text,
  utm_medium           text,
  utm_campaign         text,
  utm_content          text,
  utm_term             text,
  fbclid               text,
  fingerprint          text,
  -- Lifecycle
  first_seen_at        timestamptz not null default now(),
  opted_in_at          timestamptz,
  -- GHL metadata
  location_id          text,
  tags                 text[] default '{}',
  raw_payload          jsonb,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create index if not exists idx_gc_email         on public.ghl_contacts (lower(email));
create index if not exists idx_gc_utm_campaign  on public.ghl_contacts (utm_campaign);
create index if not exists idx_gc_fingerprint   on public.ghl_contacts (fingerprint);
create index if not exists idx_gc_fbclid       on public.ghl_contacts (fbclid);

-- Now we can wire the back-reference from page_view_events.contact_id.
do $$ begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'pve_contact_fk'
  ) then
    alter table public.page_view_events
      add constraint pve_contact_fk
      foreign key (contact_id) references public.ghl_contacts(id) on delete set null;
  end if;
end $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. ghl_pipeline_events — one row per funnel stage transition per contact.
--    Lead → AppointmentBooked → AppointmentShown → Purchase. Each row also
--    drives a Meta CAPI send (logged in capi_event_log).
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.ghl_pipeline_events (
  id                bigint generated by default as identity primary key,
  contact_id        bigint not null references public.ghl_contacts(id) on delete cascade,
  ghl_event_id      text unique,                -- if GHL provides one
  event_name        text not null check (event_name in (
                       'Lead','AppointmentBooked','AppointmentShown',
                       'AppointmentNoShow','OfferMade','Purchase','Churned')),
  event_time        timestamptz not null,
  -- Rep attribution (from round-robin user.id on appointment webhooks)
  rep_id            text,
  rep_name          text,
  rep_email         text,
  -- Deal / appointment data
  pipeline_stage    text,
  deal_value        numeric(12,2),
  currency          text default 'CAD',
  calendar_id       text,
  appointment_id    text,
  -- Linkback for joins
  utm_source        text,
  utm_medium        text,
  utm_campaign      text,
  utm_content       text,
  utm_term          text,
  raw_payload       jsonb,
  created_at        timestamptz not null default now()
);

create index if not exists idx_gpe_contact      on public.ghl_pipeline_events (contact_id);
create index if not exists idx_gpe_event_time   on public.ghl_pipeline_events (event_time desc);
create index if not exists idx_gpe_event_name   on public.ghl_pipeline_events (event_name);
create index if not exists idx_gpe_rep          on public.ghl_pipeline_events (rep_id);
create index if not exists idx_gpe_utm_campaign on public.ghl_pipeline_events (utm_campaign);
create index if not exists idx_gpe_utm_content  on public.ghl_pipeline_events (utm_content);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. meta_ad_performance — Meta Ads API daily pull, ad-level grain.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.meta_ad_performance (
  id              bigint generated by default as identity primary key,
  date            date not null,
  account_id      text not null,
  campaign_id     text not null,
  campaign_name   text,
  adset_id        text not null,
  adset_name      text,
  ad_id           text not null,
  ad_name         text,
  spend           numeric(12,2) not null default 0,
  impressions     integer not null default 0,
  clicks          integer not null default 0,
  reach           integer not null default 0,
  frequency       numeric(6,3),
  ctr             numeric(6,4),
  cpc             numeric(10,4),
  cpm             numeric(10,4),
  raw_payload     jsonb,
  synced_at       timestamptz not null default now(),
  unique (date, ad_id)
);

create index if not exists idx_map_date          on public.meta_ad_performance (date desc);
create index if not exists idx_map_campaign_name on public.meta_ad_performance (campaign_name);
create index if not exists idx_map_ad_name       on public.meta_ad_performance (ad_name);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. sales_metrics — derived daily rollup per rep, recalculated by cron.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.sales_metrics (
  id                bigint generated by default as identity primary key,
  date              date not null,
  rep_id            text not null,
  rep_name          text,
  intro_calls       integer not null default 0,
  live_intros       integer not null default 0,
  offers_made       integer not null default 0,
  closes            integer not null default 0,
  collected         numeric(12,2) not null default 0,
  recomputed_at     timestamptz not null default now(),
  unique (date, rep_id)
);

create index if not exists idx_sm_date on public.sales_metrics (date desc);
create index if not exists idx_sm_rep  on public.sales_metrics (rep_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. monthly_kpi_snapshots — one row per month, full P&L + scaling KPIs.
--    snapshot_type lets us mix real months with AI projections without
--    polluting actuals.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.monthly_kpi_snapshots (
  id                       bigint generated by default as identity primary key,
  month                    date not null,                       -- always first of month
  snapshot_type            text not null default 'actual'
                              check (snapshot_type in ('actual','projection','scenario')),
  -- Growth
  active_subscribers       integer,
  new_subscribers          integer,
  churned_subscribers      integer,
  net_new_subscribers      integer,
  churn_rate               numeric(6,4),
  mrr                      numeric(12,2),
  mrr_growth               numeric(12,2),
  mom_growth_pct           numeric(6,4),
  -- Acquisition
  ad_spend                 numeric(12,2),
  cac                      numeric(12,2),
  new_customers            integer,
  -- Revenue
  arpu                     numeric(12,2),
  revenue                  numeric(12,2),
  revenue_growth_pct       numeric(6,4),
  -- Costs
  tech_cost                numeric(12,2),
  setup_cost_total         numeric(12,2),
  setter_cost_total        numeric(12,2),
  csm_cost_total           numeric(12,2),
  commission_total         numeric(12,2),
  total_expenses           numeric(12,2),
  -- Profit
  profit_before_kd         numeric(12,2),
  kd_share                 numeric(12,2),
  net_profit               numeric(12,2),
  -- Lifetime
  avg_tenure_months        numeric(6,2),
  ltv                      numeric(12,2),
  ltv_cac_ratio            numeric(6,2),
  payback_months           numeric(6,2),
  -- Rep aggregates (for dashboard avg row)
  active_rep_count         integer,
  avg_intro_calls_per_rep  numeric(8,2),
  avg_closes_per_rep       numeric(8,2),
  avg_collected_per_rep    numeric(12,2),
  -- Source / scenario inputs (for AI replay)
  scenario_inputs          jsonb,
  computed_at              timestamptz not null default now(),
  unique (month, snapshot_type)
);

create index if not exists idx_mks_month on public.monthly_kpi_snapshots (month desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. capi_event_log — unified audit of every event sent to Meta.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.capi_event_log (
  id                bigint generated by default as identity primary key,
  event_id          text not null,
  event_name        text not null,            -- ViewContent / Lead / Schedule / AppointmentShown / Purchase
  event_time        timestamptz not null,
  source            text not null,            -- 'pixel' | 'ghl_webhook' | 'shopify_webhook' | 'manual'
  contact_id        bigint references public.ghl_contacts(id) on delete set null,
  payload           jsonb,
  response          jsonb,
  sent_ok           boolean not null default false,
  attempts          integer not null default 0,
  last_error        text,
  created_at        timestamptz not null default now(),
  unique (event_id, event_name)
);

create index if not exists idx_capi_event_time on public.capi_event_log (event_time desc);
create index if not exists idx_capi_sent_ok    on public.capi_event_log (sent_ok);

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. sync_log — tells cron jobs what was last synced from each external API.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.sync_log (
  id              bigint generated by default as identity primary key,
  source          text not null,             -- 'meta_ads' | 'tiller' | 'ghl_backfill'
  started_at      timestamptz not null default now(),
  finished_at     timestamptz,
  rows_inserted   integer not null default 0,
  rows_updated    integer not null default 0,
  status          text not null default 'running' check (status in ('running','ok','error')),
  error_message   text,
  metadata        jsonb
);

create index if not exists idx_sl_source on public.sync_log (source, started_at desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- 9. expense_config — 3-tier cost engine: defaults → per-month overrides →
--    actuals from Tiller. Calculation engine resolves in that order.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.expense_config (
  id              bigint generated by default as identity primary key,
  key             text not null,             -- e.g. 'tech_cost', 'setup_cost_per_customer'
  scope           text not null default 'default' check (scope in ('default','month','actual')),
  month           date,                      -- required when scope='month' or 'actual'
  value_numeric   numeric(12,2),
  value_pct       numeric(6,4),
  label           text,
  notes           text,
  created_at      timestamptz not null default now(),
  unique (key, scope, month)
);

-- Pre-seed defaults from the planning doc.
insert into public.expense_config (key, scope, value_numeric, value_pct, label, notes) values
  ('tech_cost',                'default', 1000.00, null, 'Tech stack (monthly)',           'Fixed: GHL, UpHex, etc.'),
  ('setup_cost_per_customer',  'default',   50.00, null, 'Onboarding setup (per new)',    'Variable per new customer'),
  ('setter_cost_per_customer', 'default',   25.00, null, 'Appointment setter (per new)',  'Variable per new customer'),
  ('csm_cost_per_active',      'default',   20.00, null, 'CSM (per active per month)',    'Variable per active customer'),
  ('kd_profit_share_pct',      'default',   null,  0.30, 'KD profit share',               '30% of profit before KD'),
  ('arpu',                     'default',  297.00, null, 'ARPU / MRR per customer',       'Headline price'),
  ('cac_target',               'default',  350.00, null, 'Target CAC',                    'For grading vs SOP'),
  ('commission_tier_1_pct',    'default',   null,  0.10, 'Closer comm <= $10k',           ''),
  ('commission_tier_2_pct',    'default',   null,  0.125,'Closer comm $10k–$25k',         ''),
  ('commission_tier_3_pct',    'default',   null,  0.15, 'Closer comm $25k+',             '')
on conflict (key, scope, month) do nothing;

-- ─────────────────────────────────────────────────────────────────────────────
-- 10. ai_model_runs — every AI call (projection/scenario/anomaly/insight)
--     with prompt, raw response, parsed output, and replayable inputs.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.ai_model_runs (
  id              bigint generated by default as identity primary key,
  run_type        text not null check (run_type in ('projection','scenario','anomaly','insight','chat')),
  prompt          text,
  inputs          jsonb,                     -- scenario knobs / context snapshot
  raw_response    text,
  parsed_output   jsonb,
  model           text default 'claude-opus-4-7',
  tokens_in       integer,
  tokens_out      integer,
  cost_usd        numeric(10,4),
  created_at      timestamptz not null default now()
);

create index if not exists idx_amr_created on public.ai_model_runs (created_at desc);
create index if not exists idx_amr_type    on public.ai_model_runs (run_type);

-- ─────────────────────────────────────────────────────────────────────────────
-- 11. cash_transactions — Tiller → Google Sheets → here. Hash-based dedup.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.cash_transactions (
  id              bigint generated by default as identity primary key,
  txn_date        date not null,
  description     text,
  amount          numeric(12,2) not null,
  account         text,
  category        text,
  expense_key     text,                       -- maps to expense_config.key when applicable
  dedup_hash      text unique not null,        -- sha256(date|amount|description|account)
  raw_row         jsonb,
  imported_at     timestamptz not null default now()
);

create index if not exists idx_ct_date    on public.cash_transactions (txn_date desc);
create index if not exists idx_ct_account on public.cash_transactions (account);

-- ─────────────────────────────────────────────────────────────────────────────
-- 12. clients — paying $297/mo clients. Source of truth for active/churn count.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.clients (
  id                    bigint generated by default as identity primary key,
  ghl_contact_id        text unique not null,
  contact_id            bigint references public.ghl_contacts(id) on delete set null,
  -- Lifecycle
  status                text not null default 'active'
                          check (status in ('active','at_risk','churned','paused')),
  started_at            timestamptz not null,
  churned_at            timestamptz,
  tenure_months         numeric(6,2)
                          generated always as (
                            case
                              when churned_at is null then null
                              else extract(epoch from (churned_at - started_at)) / 2629800.0
                            end
                          ) stored,
  -- Billing
  billing_source        text default 'external',     -- not Stripe
  external_billing_ref  text,
  mrr_value             numeric(12,2) not null default 297.00,
  last_payment_date     date,
  -- Attribution
  attributed_campaign   text,
  attributed_ad         text,
  attributed_source     text,
  rep_id                text,
  rep_name              text,
  -- Churn
  churn_reason          text check (churn_reason in (
                          'cancellation','non_payment','chargeback','other') or churn_reason is null),
  churn_source          text check (churn_source in (
                          'client_request','auto_payment','auto_chargeback','manual') or churn_source is null),
  -- GHL
  ghl_sub_account_id    text,
  notes                 text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists idx_clients_status              on public.clients (status);
create index if not exists idx_clients_started_at          on public.clients (started_at desc);
create index if not exists idx_clients_churned_at          on public.clients (churned_at desc);
create index if not exists idx_clients_attributed_campaign on public.clients (attributed_campaign);
create index if not exists idx_clients_rep                 on public.clients (rep_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- Helpful views
-- ─────────────────────────────────────────────────────────────────────────────

-- Convenience: rep daily metrics with derived rates (for /sales)
create or replace view public.v_sales_metrics_with_rates as
select
  date,
  rep_id,
  rep_name,
  intro_calls,
  live_intros,
  offers_made,
  closes,
  collected,
  case when intro_calls > 0 then live_intros::numeric / intro_calls else null end as show_rate,
  case when live_intros > 0 then offers_made::numeric / live_intros else null end as offer_rate,
  case when offers_made > 0 then closes::numeric / offers_made     else null end as close_rate,
  case when intro_calls > 0 then closes::numeric / intro_calls     else null end as call_to_close_rate,
  case when intro_calls > 0 then collected      / intro_calls      else null end as collected_per_call
from public.sales_metrics;

-- Convenience: client cohort with current activity flag
create or replace view public.v_clients_active as
select * from public.clients where status = 'active';

-- ─────────────────────────────────────────────────────────────────────────────
-- AI chat RPC: lgs_exec_sql
--   Lets the /dashboard/ask page run read-only SQL against this schema on
--   behalf of an LLM tool-call. SECURITY DEFINER so it bypasses RLS, but
--   EXECUTE is granted only to service_role — the function is unreachable
--   from anon/authenticated/PostgREST. The Next.js server is the sole caller.
--
-- Safety:
--   - Only SELECT or WITH queries accepted (case-insensitive, comments stripped)
--   - Single statement only (semicolons inside the body rejected)
--   - 10-second statement timeout per call
--   - Result capped at 1000 rows (extra rows truncated server-side)
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.lgs_exec_sql(query text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  cleaned text;
  body text;
begin
  -- Strip leading whitespace + line/block comments so callers can't sneak
  -- a write statement in behind `-- ...` or `/* ... */`.
  cleaned := regexp_replace(query, '--[^\n]*', '', 'g');
  cleaned := regexp_replace(cleaned, '/\*.*?\*/', '', 'gs');
  cleaned := ltrim(cleaned);

  if cleaned is null or length(cleaned) = 0 then
    raise exception 'Empty query';
  end if;

  if not (lower(cleaned) like 'select%' or lower(cleaned) like 'with%') then
    raise exception 'Only SELECT and WITH queries are permitted';
  end if;

  -- Reject multiple statements. Trailing semicolons + whitespace are OK.
  body := rtrim(cleaned, '; ' || E'\n' || E'\t');
  if position(';' in body) > 0 then
    raise exception 'Multiple statements not permitted';
  end if;

  perform set_config('statement_timeout', '10s', true);

  execute format(
    'select coalesce(jsonb_agg(row_to_json(t)::jsonb), ''[]''::jsonb) from (%s limit 1000) t',
    body
  )
  into result;

  return result;
end;
$$;

revoke all on function public.lgs_exec_sql(text) from public;
revoke all on function public.lgs_exec_sql(text) from anon;
revoke all on function public.lgs_exec_sql(text) from authenticated;
grant execute on function public.lgs_exec_sql(text) to service_role;
